#import "AppDelegate.h"
#import "CountryViewController.h"
#import "Product.h"

@implementation AppDelegate;

@synthesize window, navController;

- (void)dealloc
{
	[navController release];
    [window release];
    [super dealloc];
}


- (void)applicationDidFinishLaunching:(UIApplication *)application
{
    // Create and configure the window, navigation controller, and main view controller.

	// Create the master list for the main view controller.
	NSArray *listContent = [[NSArray alloc] initWithObjects:
							[Product productWithType:@"Country" name:@"Aaland Islands"                                    code:@"ALA"],
							[Product productWithType:@"Country" name:@"Afghanistan"                                       code:@"AFG"],
							[Product productWithType:@"Country" name:@"Albania"                                           code:@"ALB"],
							[Product productWithType:@"Country" name:@"Algeria"                                           code:@"DZA"],
							[Product productWithType:@"Country" name:@"American Samoa"                                    code:@"ASM"],
							[Product productWithType:@"Country" name:@"Andorra"                                           code:@"AND"],
							[Product productWithType:@"Country" name:@"Angola"                                            code:@"AGO"],
							[Product productWithType:@"Country" name:@"Anguilla"                                          code:@"AIA"],
							[Product productWithType:@"Country" name:@"Antarctica"                                        code:@"ATA"],
							[Product productWithType:@"Country" name:@"Antigua and Barbuda"                               code:@"ATG"],
							[Product productWithType:@"Country" name:@"Argentina"                                         code:@"ARG"],
							[Product productWithType:@"Country" name:@"Armenia"                                           code:@"ARM"],
							[Product productWithType:@"Country" name:@"Aruba"                                             code:@"ABW"],
							[Product productWithType:@"Country" name:@"Australia"                                         code:@"AUS"],
							[Product productWithType:@"Country" name:@"Austria"                                           code:@"AUT"],
							[Product productWithType:@"Country" name:@"Azerbaijan"                                        code:@"AZE"],
							[Product productWithType:@"Country" name:@"Bahamas"                                           code:@"BHS"],
							[Product productWithType:@"Country" name:@"Bahrain"                                           code:@"BHR"],
							[Product productWithType:@"Country" name:@"Bangladesh"                                        code:@"BGD"],
							[Product productWithType:@"Country" name:@"Barbados"                                          code:@"BRB"],
							[Product productWithType:@"Country" name:@"Belarus"                                           code:@"BLR"],
							[Product productWithType:@"Country" name:@"Belgium"                                           code:@"BEL"],
							[Product productWithType:@"Country" name:@"Belize"                                            code:@"BLZ"],
							[Product productWithType:@"Country" name:@"Benin"                                             code:@"BEN"],
							[Product productWithType:@"Country" name:@"Bermuda"                                           code:@"BMU"],
							[Product productWithType:@"Country" name:@"Bhutan"                                            code:@"BTN"],
							[Product productWithType:@"Country" name:@"Bolivia"                                           code:@"BOL"],
							[Product productWithType:@"Country" name:@"Bosnia and Herzegowina"                            code:@"BIH"],
							[Product productWithType:@"Country" name:@"Botswana"                                          code:@"BWA"],
							[Product productWithType:@"Country" name:@"Bouvet Island"                                     code:@"BVT"],
							[Product productWithType:@"Country" name:@"Brazil"                                            code:@"BRA"],
							[Product productWithType:@"Country" name:@"British Indian Ocean Territory"                    code:@"IOT"],
							[Product productWithType:@"Country" name:@"Brunei Darussalam"                                 code:@"BRN"],
							[Product productWithType:@"Country" name:@"Bulgaria"                                          code:@"BGR"],
							[Product productWithType:@"Country" name:@"Burkina Faso"                                      code:@"BFA"],
							[Product productWithType:@"Country" name:@"Burundi"                                           code:@"BDI"],
							[Product productWithType:@"Country" name:@"Cambodia"                                          code:@"KHM"],
							[Product productWithType:@"Country" name:@"Cameroon"                                          code:@"CMR"],
							[Product productWithType:@"Country" name:@"Canada"                                            code:@"CAN"],
							[Product productWithType:@"Country" name:@"Cape Verde"                                        code:@"CPV"],
							[Product productWithType:@"Country" name:@"Cayman Islands"                                    code:@"CYM"],
							[Product productWithType:@"Country" name:@"Central African Republic"                          code:@"CAF"],
							[Product productWithType:@"Country" name:@"Chad"                                              code:@"TCD"],
							[Product productWithType:@"Country" name:@"Chile"                                             code:@"CHL"],
							[Product productWithType:@"Country" name:@"China"                                             code:@"CHN"],
							[Product productWithType:@"Country" name:@"Christmas Island"                                  code:@"CXR"],
							[Product productWithType:@"Country" name:@"Cocos (Keeling) Islands"                           code:@"CCK"],
							[Product productWithType:@"Country" name:@"Colombia"                                          code:@"COL"],
							[Product productWithType:@"Country" name:@"Comoros"                                           code:@"COM"],
							[Product productWithType:@"Country" name:@"Congo, Democratic Republic of (Was Zaire)"         code:@"COD"],
							[Product productWithType:@"Country" name:@"Congo, Republic of"                                code:@"COG"],
							[Product productWithType:@"Country" name:@"Cook Islands"                                      code:@"COK"],
							[Product productWithType:@"Country" name:@"Costa Rica"                                        code:@"CRI"],
							[Product productWithType:@"Country" name:@"Cote D'ivoire"                                     code:@"CIV"],
							[Product productWithType:@"Country" name:@"Croatia (Local Name: Hrvatska)"                    code:@"HRV"],
							[Product productWithType:@"Country" name:@"Cuba"                                              code:@"CUB"],
							[Product productWithType:@"Country" name:@"Cyprus"                                            code:@"CYP"],
							[Product productWithType:@"Country" name:@"Czech Republic"                                    code:@"CZE"],
							[Product productWithType:@"Country" name:@"Denmark"                                           code:@"DNK"],
							[Product productWithType:@"Country" name:@"Djibouti"                                          code:@"DJI"],
							[Product productWithType:@"Country" name:@"Dominica"                                          code:@"DMA"],
							[Product productWithType:@"Country" name:@"Dominican Republic"                                code:@"DOM"],
							[Product productWithType:@"Country" name:@"Ecuador"                                           code:@"ECU"],
							[Product productWithType:@"Country" name:@"Egypt"                                             code:@"EGY"],
							[Product productWithType:@"Country" name:@"El Salvador"                                       code:@"SLV"],
							[Product productWithType:@"Country" name:@"Equatorial Guinea"                                 code:@"GNQ"],
							[Product productWithType:@"Country" name:@"Eritrea"                                           code:@"ERI"],
							[Product productWithType:@"Country" name:@"Estonia"                                           code:@"EST"],
							[Product productWithType:@"Country" name:@"Ethiopia"                                          code:@"ETH"],
							[Product productWithType:@"Country" name:@"Falkland Islands (Malvinas)"                       code:@"FLK"],
							[Product productWithType:@"Country" name:@"Faroe Islands"                                     code:@"FRO"],
							[Product productWithType:@"Country" name:@"Fiji"                                              code:@"FJI"],
							[Product productWithType:@"Country" name:@"Finland"                                           code:@"FIN"],
							[Product productWithType:@"Country" name:@"France"                                            code:@"FRA"],
							[Product productWithType:@"Country" name:@"French Guiana"                                     code:@"GUF"],
							[Product productWithType:@"Country" name:@"French Polynesia"                                  code:@"PYF"],
							[Product productWithType:@"Country" name:@"French Southern Territories"                       code:@"ATF"],
							[Product productWithType:@"Country" name:@"Gabon"                                             code:@"GAB"],
							[Product productWithType:@"Country" name:@"Gambia"                                            code:@"GMB"],
							[Product productWithType:@"Country" name:@"Georgia"                                           code:@"GEO"],
							[Product productWithType:@"Country" name:@"Germany"                                           code:@"DEU"],
							[Product productWithType:@"Country" name:@"Ghana"                                             code:@"GHA"],
							[Product productWithType:@"Country" name:@"Gibraltar"                                         code:@"GIB"],
							[Product productWithType:@"Country" name:@"Greece"                                            code:@"GRC"],
							[Product productWithType:@"Country" name:@"Greenland"                                         code:@"GRL"],
							[Product productWithType:@"Country" name:@"Grenada"                                           code:@"GRD"],
							[Product productWithType:@"Country" name:@"Guadeloupe"                                        code:@"GLP"],
							[Product productWithType:@"Country" name:@"Guam"                                              code:@"GUM"],
							[Product productWithType:@"Country" name:@"Guatemala"                                         code:@"GTM"],
							[Product productWithType:@"Country" name:@"Guinea"                                            code:@"GIN"],
							[Product productWithType:@"Country" name:@"Guinea-Bissau"                                     code:@"GNB"],
							[Product productWithType:@"Country" name:@"Guyana"                                            code:@"GUY"],
							[Product productWithType:@"Country" name:@"Haiti"                                             code:@"HTI"],
							[Product productWithType:@"Country" name:@"Heard and Mc Donald Islands"                       code:@"HMD"],
							[Product productWithType:@"Country" name:@"Honduras"                                          code:@"HND"],
							[Product productWithType:@"Country" name:@"Hong Kong"                                         code:@"HKG"],
							[Product productWithType:@"Country" name:@"Hungary"                                           code:@"HUN"],
							[Product productWithType:@"Country" name:@"Iceland"                                           code:@"ISL"],
							[Product productWithType:@"Country" name:@"India"                                             code:@"IND"],
							[Product productWithType:@"Country" name:@"Indonesia"                                         code:@"IDN"],
							[Product productWithType:@"Country" name:@"Iran (Islamic Republic of)"                        code:@"IRN"],
							[Product productWithType:@"Country" name:@"Iraq"                                              code:@"IRQ"],
							[Product productWithType:@"Country" name:@"Ireland"                                           code:@"IRL"],
							[Product productWithType:@"Country" name:@"Israel"                                            code:@"ISR"],
							[Product productWithType:@"Country" name:@"Italy"                                             code:@"ITA"],
							[Product productWithType:@"Country" name:@"Jamaica"                                           code:@"JAM"],
							[Product productWithType:@"Country" name:@"Japan"                                             code:@"JPN"],
							[Product productWithType:@"Country" name:@"Jordan"                                            code:@"JOR"],
							[Product productWithType:@"Country" name:@"Kazakhstan"                                        code:@"KAZ"],
							[Product productWithType:@"Country" name:@"Kenya"                                             code:@"KEN"],
							[Product productWithType:@"Country" name:@"Kiribati"                                          code:@"KIR"],
							[Product productWithType:@"Country" name:@"Korea, Democratic People's Republic of"            code:@"PRK"],
							[Product productWithType:@"Country" name:@"Korea, Republic of"                                code:@"KOR"],
							[Product productWithType:@"Country" name:@"Kuwait"                                            code:@"KWT"],
							[Product productWithType:@"Country" name:@"Kyrgyzstan"                                        code:@"KGZ"],
							[Product productWithType:@"Country" name:@"Lao People's Democratic Republic"                  code:@"LAO"],
							[Product productWithType:@"Country" name:@"Latvia"                                            code:@"LVA"],
							[Product productWithType:@"Country" name:@"Lebanon"                                           code:@"LBN"],
							[Product productWithType:@"Country" name:@"Lesotho"                                           code:@"LSO"],
							[Product productWithType:@"Country" name:@"Liberia"                                           code:@"LBR"],
							[Product productWithType:@"Country" name:@"Libyan Arab Jamahiriya"                            code:@"LBY"],
							[Product productWithType:@"Country" name:@"Liechtenstein"                                     code:@"LIE"],
							[Product productWithType:@"Country" name:@"Lithuania"                                         code:@"LTU"],
							[Product productWithType:@"Country" name:@"Luxembourg"                                        code:@"LUX"],
							[Product productWithType:@"Country" name:@"Macau"                                             code:@"MAC"],
							[Product productWithType:@"Country" name:@"Macedonia, the Former Yugoslav Republic of"        code:@"MKD"],
							[Product productWithType:@"Country" name:@"Madagascar"                                        code:@"MDG"],
							[Product productWithType:@"Country" name:@"Malawi"                                            code:@"MWI"],
							[Product productWithType:@"Country" name:@"Malaysia"                                          code:@"MYS"],
							[Product productWithType:@"Country" name:@"Maldives"                                          code:@"MDV"],
							[Product productWithType:@"Country" name:@"Mali"                                              code:@"MLI"],
							[Product productWithType:@"Country" name:@"Malta"                                             code:@"MLT"],
							[Product productWithType:@"Country" name:@"Marshall Islands"                                  code:@"MHL"],
							[Product productWithType:@"Country" name:@"Martinique"                                        code:@"MTQ"],
							[Product productWithType:@"Country" name:@"Mauritania"                                        code:@"MRT"],
							[Product productWithType:@"Country" name:@"Mauritius"                                         code:@"MUS"],
							[Product productWithType:@"Country" name:@"Mayotte"                                           code:@"MYT"],
							[Product productWithType:@"Country" name:@"Mexico"                                            code:@"MEX"],
							[Product productWithType:@"Country" name:@"Micronesia, Federated States of"                   code:@"FSM"],
							[Product productWithType:@"Country" name:@"Moldova, Republic of"                              code:@"MDA"],
							[Product productWithType:@"Country" name:@"Monaco"                                            code:@"MCO"],
							[Product productWithType:@"Country" name:@"Mongolia"                                          code:@"MNG"],
							[Product productWithType:@"Country" name:@"Montserrat"                                        code:@"MSR"],
							[Product productWithType:@"Country" name:@"Morocco"                                           code:@"MAR"],
							[Product productWithType:@"Country" name:@"Mozambique"                                        code:@"MOZ"],
							[Product productWithType:@"Country" name:@"Myanmar"                                           code:@"MMR"],
							[Product productWithType:@"Country" name:@"Namibia"                                           code:@"NAM"],
							[Product productWithType:@"Country" name:@"Nauru"                                             code:@"NRU"],
							[Product productWithType:@"Country" name:@"Nepal"                                             code:@"NPL"],
							[Product productWithType:@"Country" name:@"Netherlands"                                       code:@"NLD"],
							[Product productWithType:@"Country" name:@"Netherlands Antilles"                              code:@"ANT"],
							[Product productWithType:@"Country" name:@"New Caledonia"                                     code:@"NCL"],
							[Product productWithType:@"Country" name:@"New Zealand"                                       code:@"NZL"],
							[Product productWithType:@"Country" name:@"Nicaragua"                                         code:@"NIC"],
							[Product productWithType:@"Country" name:@"Niger"                                             code:@"NER"],
							[Product productWithType:@"Country" name:@"Nigeria"                                           code:@"NGA"],
							[Product productWithType:@"Country" name:@"Niue"                                              code:@"NIU"],
							[Product productWithType:@"Country" name:@"Norfolk Island"                                    code:@"NFK"],
							[Product productWithType:@"Country" name:@"Northern Mariana Islands"                          code:@"MNP"],
							[Product productWithType:@"Country" name:@"Norway"                                            code:@"NOR"],
							[Product productWithType:@"Country" name:@"Oman"                                              code:@"OMN"],
							[Product productWithType:@"Country" name:@"Pakistan"                                          code:@"PAK"],
							[Product productWithType:@"Country" name:@"Palau"                                             code:@"PLW"],
							[Product productWithType:@"Country" name:@"Palestinian Territory, Occupied"                   code:@"PSE"],
							[Product productWithType:@"Country" name:@"Panama"                                            code:@"PAN"],
							[Product productWithType:@"Country" name:@"Papua New Guinea"                                  code:@"PNG"],
							[Product productWithType:@"Country" name:@"Paraguay"                                          code:@"PRY"],
							[Product productWithType:@"Country" name:@"Peru"                                              code:@"PER"],
							[Product productWithType:@"Country" name:@"Philippines"                                       code:@"PHL"],
							[Product productWithType:@"Country" name:@"Pitcairn"                                          code:@"PCN"],
							[Product productWithType:@"Country" name:@"Poland"                                            code:@"POL"],
							[Product productWithType:@"Country" name:@"Portugal"                                          code:@"PRT"],
							[Product productWithType:@"Country" name:@"Puerto Rico"                                       code:@"PRI"],
							[Product productWithType:@"Country" name:@"Qatar"                                             code:@"QAT"],
							[Product productWithType:@"Country" name:@"Reunion"                                           code:@"REU"],
							[Product productWithType:@"Country" name:@"Romania"                                           code:@"ROU"],
							[Product productWithType:@"Country" name:@"Russian Federation"                                code:@"RUS"],
							[Product productWithType:@"Country" name:@"Rwanda"                                            code:@"RWA"],
							[Product productWithType:@"Country" name:@"Saint Helena"                                      code:@"SHN"],
							[Product productWithType:@"Country" name:@"Saint Kitts and Nevis"                             code:@"KNA"],
							[Product productWithType:@"Country" name:@"Saint Lucia"                                       code:@"LCA"],
							[Product productWithType:@"Country" name:@"Saint Pierre and Miquelon"                         code:@"SPM"],
							[Product productWithType:@"Country" name:@"Saint Vincent and the Grenadines"                  code:@"VCT"],
							[Product productWithType:@"Country" name:@"Samoa"                                             code:@"WSM"],
							[Product productWithType:@"Country" name:@"San Marino"                                        code:@"SMR"],
							[Product productWithType:@"Country" name:@"Sao Tome and Principe"                             code:@"STP"],
							[Product productWithType:@"Country" name:@"Saudi Arabia"                                      code:@"SAU"],
							[Product productWithType:@"Country" name:@"Senegal"                                           code:@"SEN"],
							[Product productWithType:@"Country" name:@"Serbia and Montenegro"                             code:@"SCG"],
							[Product productWithType:@"Country" name:@"Seychelles"                                        code:@"SYC"],
							[Product productWithType:@"Country" name:@"Sierra Leone"                                      code:@"SLE"],
							[Product productWithType:@"Country" name:@"Singapore"                                         code:@"SGP"],
							[Product productWithType:@"Country" name:@"Slovakia"                                          code:@"SVK"],
							[Product productWithType:@"Country" name:@"Slovenia"                                          code:@"SVN"],
							[Product productWithType:@"Country" name:@"Solomon Islands"                                   code:@"SLB"],
							[Product productWithType:@"Country" name:@"Somalia"                                           code:@"SOM"],
							[Product productWithType:@"Country" name:@"South Africa"                                      code:@"ZAF"],
							[Product productWithType:@"Country" name:@"South Georgia and the South Sandwich Islands"      code:@"SGS"],
							[Product productWithType:@"Country" name:@"Spain"                                             code:@"ESP"],
							[Product productWithType:@"Country" name:@"Sri Lanka"                                         code:@"LKA"],
							[Product productWithType:@"Country" name:@"Sudan"                                             code:@"SDN"],
							[Product productWithType:@"Country" name:@"Suriname"                                          code:@"SUR"],
							[Product productWithType:@"Country" name:@"Svalbard and Jan Mayen Islands"                    code:@"SJM"],
							[Product productWithType:@"Country" name:@"Swaziland"                                         code:@"SWZ"],
							[Product productWithType:@"Country" name:@"Sweden"                                            code:@"SWE"],
							[Product productWithType:@"Country" name:@"Switzerland"                                       code:@"CHE"],
							[Product productWithType:@"Country" name:@"Syrian Arab Republic"                              code:@"SYR"],
							[Product productWithType:@"Country" name:@"Taiwan"                                            code:@"TWN"],
							[Product productWithType:@"Country" name:@"Tajikistan"                                        code:@"TJK"],
							[Product productWithType:@"Country" name:@"Tanzania, United Republic of"                      code:@"TZA"],
							[Product productWithType:@"Country" name:@"Thailand"                                          code:@"THA"],
							[Product productWithType:@"Country" name:@"Timor-Leste"                                       code:@"TLS"],
							[Product productWithType:@"Country" name:@"Togo"                                              code:@"TGO"],
							[Product productWithType:@"Country" name:@"Tokelau"                                           code:@"TKL"],
							[Product productWithType:@"Country" name:@"Tonga"                                             code:@"TON"],
							[Product productWithType:@"Country" name:@"Trinidad and Tobago"                               code:@"TTO"],
							[Product productWithType:@"Country" name:@"Tunisia"                                           code:@"TUN"],
							[Product productWithType:@"Country" name:@"Turkey"                                            code:@"TUR"],
							[Product productWithType:@"Country" name:@"Turkmenistan"                                      code:@"TKM"],
							[Product productWithType:@"Country" name:@"Turks and Caicos Islands"                          code:@"TCA"],
							[Product productWithType:@"Country" name:@"Tuvalu"                                            code:@"TUV"],
							[Product productWithType:@"Country" name:@"Uganda"                                            code:@"UGA"],
							[Product productWithType:@"Country" name:@"Ukraine"                                           code:@"UKR"],
							[Product productWithType:@"Country" name:@"United Arab Emirates"                              code:@"ARE"],
							[Product productWithType:@"Country" name:@"United Kingdom"                                    code:@"GBR"],
							[Product productWithType:@"Country" name:@"United States"                                     code:@"USA"],
							[Product productWithType:@"Country" name:@"United States Minor Outlying Islands"              code:@"UMI"],
							[Product productWithType:@"Country" name:@"Uruguay"                                           code:@"URY"],
							[Product productWithType:@"Country" name:@"Uzbekistan"                                        code:@"UZB"],
							[Product productWithType:@"Country" name:@"Vanuatu"                                           code:@"VUT"],
							[Product productWithType:@"Country" name:@"Vatican City State (Holy See)"                     code:@"VAT"],
							[Product productWithType:@"Country" name:@"Venezuela"                                         code:@"VEN"],
							[Product productWithType:@"Country" name:@"Viet Nam"                                          code:@"VNM"],
							[Product productWithType:@"Country" name:@"Virgin Islands (British)"                          code:@"VGB"],
							[Product productWithType:@"Country" name:@"Virgin Islands (U.S.)"                             code:@"VIR"],
							[Product productWithType:@"Country" name:@"Wallis and Futuna Islands"                         code:@"WLF"],
							[Product productWithType:@"Country" name:@"Western Sahara"                                    code:@"ESH"],
							[Product productWithType:@"Country" name:@"Yemen"                                             code:@"YEM"],
							[Product productWithType:@"Country" name:@"Zambia"                                            code:@"ZMB"],
							[Product productWithType:@"Country" name:@"Zimbabwe"                                          code:@"ZWE"],							
							nil];
					
	
	// Create and configure the main view controller.
	CountryViewController *countryViewController = [[CountryViewController alloc] initWithNibName:@"MainView" bundle:nil];
	countryViewController.listContent = listContent;
	[listContent release];
	
	// Add create and configure the navigation controller.
	UINavigationController *navigationController = [[UINavigationController alloc] initWithRootViewController:countryViewController];
	self.navController = navigationController;
	[navigationController release];
	
	// Configure and display the window.
	[window addSubview:navController.view];
	[window makeKeyAndVisible];
}


@end
